spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/matchdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info